### ISSUE TITLE
Error running papnt doi

### ISSUE THREAD

**Issue by cenotence** [issakuss/papnt#1]
when i running `papnt doi` I have:

```
% papnt doi
First is expected to be rich_text.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages/904eac8c-5d61-466e-b2fa-6a763d8b5bd2'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/papnt/mainfunc.py", line 35, in _update_record_from_doi
    database.update(id_record, prop)
  File "/opt/homebrew/lib/python3.10/site-packages/papnt/database.py", line 41, in update
    self.notion.pages.update(page_id=page_id, properties=prop)
  File "/opt/homebrew/lib/python3.10/site-packages/notion_client/api_endpoints.py", line 220, in update
    return self.parent.request(
  File "/opt/homebrew/lib/python3.10/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/opt/homebrew/lib/python3.10/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: First is expected to be rich_text.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/papnt", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/papnt/cli.py", line 56, in doi
    update_unchecked_records_from_doi(database, config['propnames'])
  File "/opt/homebrew/lib/python3.10/site-packages/papnt/mainfunc.py", line 48, in update_unchecked_records_from_doi
    _update_record_from_doi(database, doi, record['id'], propnames)
  File "/opt/homebrew/lib/python3.10/site-packages/papnt/mainfunc.py", line 39, in _update_record_from_doi
    raise ValueError(f'Error while updating record: {name}')
ValueError: Error while updating record: Kawashima2022 
```

Any idea? FYI, I have python 3.10.  thanks

**Comment by issakuss** [comment]
Thanks for using my tool!
I apologize for the mistake in the [instruction](https://qiita.com/issakuss/items/2e69f2da040cb35ed0d3#notion側の準備).
You also need to set the type of the "First" property (row) as "Select".
Could you please modify the "First" property in your Notion database to be of the "Select" type and give it another try?

**Comment by cenotence** [comment]
Thank you for your prompt response. Now, it was successfully executed! 
This is a very nice tool. I am very thankful for this!

btw, are arXiv papers not supported?

**Comment by issakuss** [comment]
> Thank you for your prompt response. Now, it was successfully executed!
> This is a very nice tool. I am very thankful for this!

Great! I'm so happy to hear that!

> btw, are arXiv papers not supported?

Unfortunately, no, they aren't because the crossrefapi doesn't support the ArXiv identifier.
However, since ArXiv provides an API, it doesn't seem too difficult to implement.
I will attempt to add support for ArXiv papers, but please note that it may take a long time to complete.

**Comment by cenotence** [comment]
Thank you! I look forward to your implementation of support for the ArXiv paper and please take your own pace!
